### ISSUE TITLE
Does this plugin support tado X devices?

### ISSUE THREAD

**Issue by amidabrian51** [SeydX/homebridge-tado-platform#179]
### Current Situation

I have added the bridge in homekit expecting to see my radiator controllers.  However, I don't see anything. Am I missing something?  It does not seem clear what is the next step after you add the plugin in homekit.  Any help would be appreciated as I have tried using matter for Homekit and it is hopeless.

### Logs

```markdown
Setup Payload:
X-HM://0023NYMV5H6A4
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 118-07-553 │     
    └────────────┘     
                       
[10/31/2025, 10:20:12 PM] Homebridge v1.11.1 (HAP v0.14.0) (Homebridge 022D) is running on port 51960.
[10/31/2025, 10:20:12 PM] [TadoPlatform] Launched child bridge with PID 31579
[10/31/2025, 10:20:12 PM] Registering platform '@homebridge-plugins/homebridge-tado.TadoPlatform'
[10/31/2025, 10:20:12 PM] [TadoPlatform] Loaded @homebridge-plugins/homebridge-tado v8.5.0 child bridge successfully
[10/31/2025, 10:20:12 PM] Loaded 0 cached accessories from cachedAccessories.0EE9F278C19D.
[10/31/2025, 10:20:12 PM] [TadoPlatform] Skipping persistence of tado states for home 1962818: zone states are empty.
[10/31/2025, 10:20:12 PM] Homebridge v1.11.1 (HAP v0.14.0) (TadoPlatform 7D62) is running on port 46368.
[10/31/2025, 10:20:12 PM] [TadoPlatform] Tado API counter: 0
[10/31/2025, 10:25:12 PM] [TadoPlatform] Skipping persistence of tado states for home 1962818: zone states are empty.
```

### Configuration

```json
"platform": "TadoPlatform",
    "name": "TadoPlatform",
    "homes": [
        {
            "id": 1962818,
            "name": "Home",
            "username": "home",
            "polling": 300,
            "zones": [],
            "presence": {
                "anyone": false,
                "accTypeAnyone": "OCCUPANCY",
                "user": [
                    {
                        "active": false,
                        "name": "Katy’s",
                        "accType": "OCCUPANCY"
                    },
                    {
                        "active": false,
                        "name": "Brian’s iPhone 2",
                        "accType": "OCCUPANCY"
                    }
                ]
            },
            "weather": {
                "temperatureSensor": false,
                "solarIntensity": false,
                "accTypeSolarIntensity": "LIGHTBULB"
            },
            "extras": {
                "centralSwitch": false,
                "runningInformation": false,
                "boostSwitch": false,
                "sheduleSwitch": false,
                "turnoffSwitch": false,
                "presenceLock": false,
                "accTypePresenceLock": "ALARM",
                "childLockSwitches": []
            },
            "telegram": {
                "active": false
            },
            "temperatureUnit": "CELSIUS",
            "geolocation": {
                "longitude": "-0.3598636",
                "latitude": "51.4408769"
            }
        }
    ],
    "_bridge": {
        "username": "0E:E9:F2:78:C1:9D",
        "port": 46368,
        "name": "TadoPlatform 7D62"
    }
}
```

### Environment

- OS:
- Software:
- Node:
- npm:

### Process Supervisor

hb-service

**Comment by smart7324** [comment]
@amidabrian51 It seems to me, that your username is incorrect. The username has to be the username which you are using to sign into the tado web app at https://my.tado.com

In your config you are using `home` as username. 

I would suggest you complete the setup of the plugin through the UI, where you sign into your tado account and follow the steps.

**Comment by amidabrian51** [comment]
I have setup two zones/rooms and I can now see them in homekit.  Although, when I try to change the temperature nothing seems to happen.  Attached is a log file.  Again any help would be appreciated.

[@homebridge-plugins_homebridge-tado.log.txt](https://github.com/user-attachments/files/23283699/%40homebridge-plugins_homebridge-tado.log.txt)

**Comment by smart7324** [comment]
@amidabrian51 I still think that you have an invalid configuration, as the plugin didn't receive valid zone states, as it is written into your log: `Skipping persistence of tado states for home 1962818: zone states are empty.`

Also there are 404 not found errors when polling the zone state. How did you configure the plugin? Did you follow the steps in the UI? Are you using the authentication through the browser?

**Comment by amidabrian51** [comment]
I'm obviously being very very very thick and stupid.  As every time I do this it does not recognise my login details. I am probably the only person on the planet that does not get this!!!! So it asks me for my username which is my email? The I am following the steps.  I have a question in the perfect world if and when the authentication is a success it should fill out the zones automatically ? `Failed to update zones: Cannot read properties of undefined (reading 'setting')
[11/1/2025, 8:30:26 PM] [TadoPlatform] Tado API counter: 11
[11/1/2025, 8:30:57 PM] [TadoPlatform] Home Halllway Heater: Temperature: 20
[11/1/2025, 8:30:58 PM] [TadoPlatform] Home: API Request [GET /api/v2/homes/1962818/zones/1132098560/state] - FAILED: Request failed with status code 404 (Not Found): GET https://my.tado.com/api/v2/homes/1962818/zones/1132098560/state
[11/1/2025, 8:30:58 PM] [TadoPlatform] Failed to set states: Request failed with status code 404 (Not Found): GET https://my.tado.com/api/v2/homes/1962818/zones/1132098560/state
[11/1/2025, 8:30:58 PM] [TadoPlatform] Skipping persistence of tado states file for home 1962818: zone states are empty.
[11/1/2025, 8:30:58 PM] [TadoPlatform] Failed to update zones: Cannot read properties of undefined (reading 'setting')`

**Comment by amidabrian51** [comment]
I will send you screenshots of what is happening. Thanks for taking the time to help.BrianSent from the iPadOn 1 Nov 2025, at 18:39, smart7324 ***@***.***> wrote:﻿smart7324 left a comment (homebridge-plugins/homebridge-tado#179)
@amidabrian51 I still think that you have an invalid configuration, as the plugin didn't receive valid zone states, as it is written into your log: Skipping persistence of tado states for home 1962818: zone states are empty.
Also there are 404 not found errors when polling the zone state. How did you configure the plugin? Did you follow the steps in the UI? Are you using the authentication through the browser?

**Comment by smart7324** [comment]
@amidabrian51 did you enter your username here in the config UI and then press on `Next`?

<img width="789" height="603" alt="Image" src="https://github.com/user-attachments/assets/d778ebaa-d3c3-4a15-989c-6727e8ed22e9" />

After that it should ask you to open a URL in your browser, login with your tado account and approve the device:

<img width="777" height="600" alt="Image" src="https://github.com/user-attachments/assets/e8afacf1-2c6a-4cc1-b16c-19d0792954e2" />

You will also get messages in your log with the same instructions:

```
[11/2/2025, 11:33:25 AM] [Homebridge UI] [@homebridge-plugins/homebridge-tado] Executing /fullAuthentication
[11/2/2025, 11:33:25 AM] [Homebridge UI] [@homebridge-plugins/homebridge-tado] Requesting device authorization...
[11/2/2025, 11:33:26 AM] [Homebridge UI] [@homebridge-plugins/homebridge-tado] Open the following URL in your browser, click "submit" and log in to your tado° account "test@mail.com": https://login.tado.com/oauth2/device?user_code=XXXXXX
[11/2/2025, 11:33:26 AM] [Homebridge UI] [@homebridge-plugins/homebridge-tado] Incoming Request: /exec
[11/2/2025, 11:33:26 AM] [Homebridge UI] [@homebridge-plugins/homebridge-tado] Executing /waitForAuthentication
[11/2/2025, 11:33:31 AM] [Homebridge UI] [@homebridge-plugins/homebridge-tado] Waiting for confirmation...
```

I checked your log and there is no such message.

As soon as it is connected to the API it should start receiving your zones and adding them to your configuration.

In your config.json the `zones` property is still empty: `"zones": [],`

Please give it another try by following the screenshot instructions from above. If you authenticated successfully and it's still not working, we would have to investigate further.

**Comment by amidabrian51** [comment]
This is what is happening when I am trying to login.

<img width="451" height="286" alt="Image" src="https://github.com/user-attachments/assets/f23f4345-101c-4f36-8366-1694fae6cb7e" />
I press start and get this screen.

<img width="451" height="387" alt="Image" src="https://github.com/user-attachments/assets/cc7270e6-3990-4d0d-b15b-ea056fa58cb9" />
I input my email address then press next.

<img width="451" height="378" alt="Image" src="https://github.com/user-attachments/assets/fd9f5be6-cef5-4660-bcd0-4f4af5a12b92" />
I am not seeing the message  `open the following url in the browser...`. Although, I might have seen it when I first tried the plugin.  Then after that I am getting this.

<img width="451" height="340" alt="Image" src="https://github.com/user-attachments/assets/68549219-2552-4c29-943d-6a525b9d1dd6" />
after that I can see that that this probably has not worked.

<img width="451" height="432" alt="Image" src="https://github.com/user-attachments/assets/550f977c-35c6-41a6-8e19-8d66501af864" />

**Comment by amidabrian51** [comment]
Thanks for looking into this for me. Just wondered if had a chance read my response.Regards Brian Sent from my iPhoneOn 2 Nov 2025, at 11:00, smart7324 ***@***.***> wrote:﻿smart7324 left a comment (homebridge-plugins/homebridge-tado#179)
@amidabrian51 did you enter your username here in the config UI and then press on Next?
Bildschirmfoto.2025-11-02.um.11.52.46.png (view on web)
After that it should ask you to open a URL in your browser, login with your tado account and approve the device:
Bildschirmfoto.2025-11-02.um.11.53.39.png (view on web)
You will also get messages in your log with the same instructions:
[11/2/2025, 11:33:25 AM] [Homebridge UI] ***@***.***/homebridge-tado] Executing /fullAuthentication
[11/2/2025, 11:33:25 AM] [Homebridge UI] ***@***.***/homebridge-tado] Requesting device authorization...
[11/2/2025, 11:33:26 AM] [Homebridge UI] ***@***.***/homebridge-tado] Open the following URL in your browser, click "submit" and log in to your tado° account ***@***.***": https://login.tado.com/oauth2/device?user_code=XXXXXX
[11/2/2025, 11:33:26 AM] [Homebridge UI] ***@***.***/homebridge-tado] Incoming Request: /exec
[11/2/2025, 11:33:26 AM] [Homebridge UI] ***@***.***/homebridge-tado] Executing /waitForAuthentication
[11/2/2025, 11:33:31 AM] [Homebridge UI] ***@***.***/homebridge-tado] Waiting for confirmation...

I checked your log and there is no such message.
As soon as it is connected to the API it should start receiving your zones and adding them to your configuration.
In your config.json the zones property is still empty: "zones": [],
Please give it another try by following the screenshot instructions from above. If you authenticated successfully and it's still not working, we would have to investigate further.

**Comment by smart7324** [comment]
@amidabrian51 I have checked your issue on a new clean homebridge install and tried to configure the plugin. After authentication via browser the plugin successfully polled the zones and added them to the config.json. I don't understand why there are no zones in your config `zones: []`.

However I have tried to mimic the same situation as you have, by deleting my zones from the config:

<img width="466" height="81" alt="Image" src="https://github.com/user-attachments/assets/53c54fb7-68eb-4d73-9064-28148ebd717d" />

You can trigger a re-sync of your tado devices by pressing this icon in the config UI:

<img width="790" height="515" alt="Image" src="https://github.com/user-attachments/assets/c8f7c1fc-8bfd-4a6e-b977-40997797eb7e" />

After that it should automatically add the zones you have configured in tado to your config:

<img width="428" height="116" alt="Image" src="https://github.com/user-attachments/assets/dbf4555e-afd1-460f-be18-bdda18ac3b10" />

Please let me know if that worked for you.

**Comment by amidabrian51** [comment]
Unfortunately it is still not working!

<img width="451" height="156" alt="Image" src="https://github.com/user-attachments/assets/75131e68-a939-420d-8724-016eee762009" />
Then started the process.

<img width="451" height="287" alt="Image" src="https://github.com/user-attachments/assets/2538f8f6-e39c-41ef-b5c7-9ecb9fb73581" />
inputted my email address for Tado.

<img width="451" height="385" alt="Image" src="https://github.com/user-attachments/assets/a9fa49db-8fd1-462a-a906-079fff665b71" />
Still don't get the login url on the next screen.

<img width="451" height="375" alt="Image" src="https://github.com/user-attachments/assets/63b4780a-0e07-45ef-8476-55473dd05977" />
Do you think there is someting wrong with my version of Homebridge.  If so how do I do a fresh install?

**Comment by amidabrian51** [comment]
I tried a fresh install of hb and deleted the ~/.homebridge folder.  I installed the plugin input my email address and then got the authentication url.  Pressed the url.  This had a screen with the code on it.  Then went got this.

<img width="1428" height="916" alt="Image" src="https://github.com/user-attachments/assets/e6dc8030-c530-474c-ada8-22285242ce64" />
Now I went back to my did all the restart process and scanned the QR code.  Went back to my see if my zones are there and they are not.  I have refreshed a couple of times.  Now I did notice that if I checked back to the "Connect your device" Tado page I back space and saw this.

<img width="3284" height="774" alt="Image" src="https://github.com/user-attachments/assets/10df44c7-2f9a-43d5-a247-8b6092042f2f" />
Hope this helps.  Might try another uninstall and reinstall.

**Comment by blitzmax01** [comment]
Hey, I have the same issue as the user above. If I use my username the connection is successful and the settings get imported, but not my zones. I use the new generation of the Tado devices which are Matter compatible (Tado X). Is it possible that this causes the problem?

**Comment by smart7324** [comment]
> Hey, I have the same issue as the user above. If I use my username the connection is successful and the settings get imported, but not my zones. I use the new generation of the Tado devices which are Matter compatible (Tado X). Is it possible that this causes the problem?

@blitzmax01 thanks for reporting—this might be an important detail. I’m not sure if the Tado X devices return the same data when queried through the API.

@amidabrian51, are you also using Tado X devices?

To help investigate this issue further, I’ve released a new version that adds more detailed debug logs to the apiCall function. Please install the latest version v8.7.1, enable debug mode, try adding your home again (or click the re-sync button), and share the logs here.

**Comment by amidabrian51** [comment]
@smart7324 I am also using Tado X devices.  I will install the new version.

**Comment by amidabrian51** [comment]
Not sure if I got the right logs

[@homebridge-plugins_homebridge-tado.log (3).txt](https://github.com/user-attachments/files/23345812/%40homebridge-plugins_homebridge-tado.log.3.txt)

Don't know if this helps.  It is still not working.

**Comment by smart7324** [comment]
> Not sure if I got the right logs
> 
> [@homebridge-plugins_homebridge-tado.log (3).txt](https://github.com/user-attachments/files/23345812/%40homebridge-plugins_homebridge-tado.log.3.txt)
> 
> Don't know if this helps. It is still not working.

@amidabrian51 Yes, I only added logs, didn’t change something. You need to activate the debug mode in the config and then re-sync the home or configure a new one. I need these logs to see the API response.

**Comment by amidabrian51** [comment]
I have ticked the debug and here is the log.

[@homebridge-plugins_homebridge-tado.log (4).txt](https://github.com/user-attachments/files/23346025/%40homebridge-plugins_homebridge-tado.log.4.txt)
Thanks for looking into this.  Do you think they have changed the API for Tado X devices?

**Comment by smart7324** [comment]
@amidabrian51 there is still nothing relevant in your logs. Did you add a new home or press re-sync on the existing? There were no calls made.

I’m not sure if anybody has used this plugin to control Tado X devices.

**Comment by amidabrian51** [comment]
I pressed re-sync on the existing.  Basically I have done a fresh install of Homebridge twice as that's the only way I can see the url when I setup the plugin.  I notice it goes to the code page see below.  Although, as I said before it does not ask me to signin  (middle picture). It goes straight to "successfully connected device"  .  Not sure if that is relevant.

<img width="1594" height="444" alt="Image" src="https://github.com/user-attachments/assets/d029d219-3106-4aae-89c0-db91553b7935" />

**Comment by smart7324** [comment]
@amidabrian51 yes it's normal that it directly goes to number 3 if you're already logged in into your tado account on your browser session. I still need the logs about the API calls that are being made when the plugin is initializing the zones. Maybe @blitzmax01 can also provide some logs?

**Comment by amidabrian51** [comment]
@smart7324 I think I have followed the process correctly and provided the correct logs.  I pressed the debub thingy and then pressed the refresh. Hopefully, @blitzmax01 can provide some clues as to what is going wrong.  Just wondered do Tado officially support an API ?

**Comment by blitzmax01** [comment]
@smart7324 - Thanks for the quick help. But I am currently struggling to generate a log while fetching my home from tado. I reinstalled the newest version and activated debug in the plugin and for my whole homebridge. Unfortunately if I fetch the data from Tado no logs are generated while doing this for the plugin. The home is fetched corretly from tado but nothing logs are created while doing it.

**Comment by smart7324** [comment]
Okay, thanks. I will have a look and come back to you.

**Comment by blitzmax01** [comment]
[Tado_debug.log.txt](https://github.com/user-attachments/files/23375739/Tado_debug.log.txt)

This is everything I got

I deleted the unnecessary things - I hope it helps

**Comment by smart7324** [comment]
Hello @blitzmax01, thanks a lot for your effort! Unfortunately, the logs don’t provide enough information since they don’t include any API requests or responses. I need to investigate why these entries aren’t showing up in your log files, even with debug mode enabled.

I’ll definitely look into this over the next few days, as I’m a bit busy at the moment.

**Comment by blitzmax01** [comment]
Don't worry, thanks a lot!

**Comment by amidabrian51** [comment]
I agree with the @blitzmax01 remarks.  Thank you @smart7324 for looking into this.  Hopefully we can get a successful resolution to this.

**Comment by blitzmax01** [comment]
Here are some more logs after the configuration was done, but no zones are active, you can see the API-Calls:

[@homebridge-plugins_homebridge-tado.log.txt](https://github.com/user-attachments/files/23422094/%40homebridge-plugins_homebridge-tado.log.txt)

As an additional information, the Tado X devices are native Apple Home compatible through Matter. You can change the temperature and turn the heating on and off. What would be nice is a button to reenable the schedule. The only buttons that work currently at the moment is the "Presence Button". The other switches like the Central Switch don't work.

**Comment by amidabrian51** [comment]
@blitzmax01 wish I could see those API calls in my log?  I have tried adding them to Apple Home but with no success.  They appear for an instant then it says they are unresponsive.  I have a homepod mini which can act as a Matter controller.  Not sure if this is working?

**Comment by smart7324** [comment]
@blitzmax01 Thanks for your efforts!  
@amidabrian51  

I did some investigation into the **tado X** devices. Unfortunately, they use a completely different API endpoint (`https://hops.tado.com`) and different methods compared to the regular tado devices.  

Because of this, I have to inform you that **this plugin currently does not support tado X devices**. Implementing support for them would require a significant development effort, which I’m not able to take on at the moment.  

You can find more information about the differences for tado X devices here:  
- [tado X – API differences (wiki)](https://github.com/kritsel/tado-openapispec-v2/wiki/tado-X)  
- [Swagger documentation](https://kritsel.github.io/tado-openapispec-v2/swagger.html#/)  
- [Postman collection & additional resources](https://github.com/gedhi/tadox-postman-collection?tab=readme-ov-file#additional-resources)  

I’ll also add this information to the documentation to avoid confusion in the future.  

Thanks for your understanding!

**Comment by blitzmax01** [comment]
Good morning smart7324,thanks for the info, I completely understand that. But I can confirm that it is still possible to use the Weather-data and the Home and Away mode. Have a nice weekend !Best RegardsMaxAm 08.11.2025 um 08:04 schrieb smart7324 ***@***.***>:﻿smart7324 left a comment (homebridge-plugins/homebridge-tado#179)
@blitzmax01 Thanks for your efforts!
@amidabrian51
I did some investigation into the tado X devices. Unfortunately, they use a completely different API endpoint (https://hops.tado.com) and different methods compared to the regular tado devices.
Because of this, I have to inform you that this plugin currently does not support tado X devices. Implementing support for them would require a significant development effort, which I’m not able to take on at the moment.
You can find more information about the differences for tado X devices here:

tado X – API differences (wiki)
Swagger documentation
Postman collection & additional resources

I’ll also add this information to the documentation to avoid confusion in the future.
Thanks for your understanding!

**Comment by smart7324** [comment]
@blitzmax01 yes, that’s correct. These functions use the `/api/v2` endpoint, as they are home-specific, so they will work even with tado X devices.

Thanks for confirming and a great weekend for you, too!

**Comment by amidabrian51** [comment]
@smart7324 and @blitzmax01  thankyou for your efforts.  I kinda feared that this would be the case.  I will just have to stick with using the Tado app for now.  Just a shame that Matter isn't more stable.  Well it does work me.  Have great weekend.

**Comment by smart7324** [comment]
@amidabrian51 You're welcome! Have a great weekend!
